### PR TITLE
fix(regex): fix regex for urls with ports #142

### LINKED ISSUE #142: Bug: Cannot Connect w/ Port in URL
## Bug Description

I've self-hosted the repository on a docker. As a result, there is a special port to connect to the GitLab repository: port number 5022. 

The URL to clone the repository looks like this:

ssh://git@lab.xxx.yy:5022/project_group/project.git

My current authentication information are set like this:

```
auth_token=TOKEN
project_id=43
gitlab_url=https://lab.xxx.yy
```

When I'm trying to open the review I'm getting the error:

gitlab.nvim: 2023/12/15 05:47:22 Failed to initialize project settings: Error getting project at ssh://git@lab.xxx.yy:5022/project_group/project.git%!(EXTRA *gitlab.ErrorResponse=GET https://lab.xxx.yy/api/v4/projects/5022/project_group/
project: 404 {message: 404 Project Not Found})  

As you can see in the request, the plugin mixed the port from SSH (5022) as a part of the path to the project. If I clone the repo as https://..., everything works fine.

### PR DESCRIPTION
**Pull request by Zombiefleischer**
fix #142

### CODE REVIEW

**Comment by harrisoncramer** [comment]
Nice, thank you for submitting this! Could you please add a couple of test cases to `git_test.go` which is where this regex is tested? I don't have the ability to test this since I'm not running this project with a PORT but I'll assume that if it's working for you and passes the test then it's good to ship.

**Comment by Zombiefleischer** [comment]
The problem is, it's not working :sweat_smile: 
In my regex editor it works perfectly and also the script test I run, but as soon as I implemented it into the module, it seems to ignore it.
I found a workaround for the time being:
```git
[core]
  sshCommand = ssh -p 8022
```

**Comment by harrisoncramer** [comment]
I'm not sure I understand -- you're saying that your MR does not let you connect to Gitlab, _unless_ you additionally provide the following change to your `.gitconfig` file?

**Comment by Zombiefleischer** [comment]
My initial problem was the custom GitLab port on our self-hosted GitLab. After searching in other issues, I found that someone solved it by modifying the regex, but did not provide the regex themselves. So I wrote one myself and to prevent others running into this issue I thought let's put it into an MR. During testing, I found out, that it did not work, which was weird. On master/main branch, it gave me the error, that it does not run on master/main. On a branch, it gave me the following error:
```
gitlab.nvim: 2024/03/26 16:35:39 Failed to initialize project settings: Error getting project at ssh://git@git.<redacted>:8022/<user>/<project>.git%!(EXTRA *gitlab.ErrorResponse=GET https://git.<redacted>/api/v4/projects/
8022/<user>/<project>: 404 {message: 404 Project Not Found})
```
After that, I tried a simple script in go (with help from ChatGPT, since I'm not a go developer):
<details><summary>regex.go</summary>
<p>

```go
package main

import (
    "fmt"
    "regexp"
)

func main() {
    testURLs := []string{
        "https://gitlab.com/namespace/dummy-test-repo.git",
        "git@gitlab.com:namespace/dummy-test-repo.git",
        "ssh://git@gitlab.com/namespace/dummy-test-repo.git",
        "ssh://git@gitlab.com/namespace/subnamespace/dummy-test-repo",
        "https://git@gitlab.com/namespace/subnamespace/dummy-test-repo.git",
        "git@git@gitlab.com:namespace/subnamespace/dummy-test-repo.git",
        "ssh://git@git.testrepo.net:8022/user/project.git",
    }

    re := regexp.MustCompile(`(?:^https?:\/\/|^ssh:\/\/|^git@)(?:[^\/:]+)(?::\d+)?[\/:](.*)\/([^\/]+?)(?:\.git)?$`)

    for _, url := range testURLs {
        matches := re.FindStringSubmatch(url)
        if len(matches) != 3 {
            fmt.Printf("Invalid Git URL format: %s\n", url)
        } else {
            namespace := matches[1]
            projectName := matches[2]
            fmt.Printf("URL: %s, Namespace: %s, Project Name: %s\n", url, namespace, projectName)
        }
    }
}
``` 

</p>
</details> 

There it worked perfectly. A little bit out of ideas (and out of time), I found the workaround solution with the git config:
```git
[core]
	sshCommand = ssh -p 8022
[remote "origin"]
	url = ssh://git@git.<gitlab>.net/<user>/<project>.git
```
After that I proposed the MR and hoped you had some idea, where this issue could be solved. Since then, I worked with the workaround and had not tried to find a solution to this.

**Pull request closed without merging**
