### PR TITLE
fix: Fixes MR selection if there are multiple targets

### PR DESCRIPTION
**Pull request by harrisoncramer**
Addresses #319

### CODE REVIEW

**Comment by harrisoncramer** [comment]
Hey @jakubbortlik I've fixed that issue.

If you are just opening the reviewer in a merge request and there are multiple options, I'll throw an error in the Go server and tell you to choose one via the `choose_merge_request` option. The `choose_merge_request` function now sets a value in the shared state that specifies the target for the MR selector, which is passed along to the server.

This should resolve your issue, can you please give it a try?

**Comment by jakubbortlik** [comment]
Hi Harrison, I confirm that in this branch the issue is solved. Thanks!

**Comment by jakubbortlik** [comment]
Maybe you could show the error and run `choose_merge_request` right away. I believe that's what most users will want to do anyway.

**Comment by harrisoncramer** [comment]
Yeah, I thought about having that, but it would add some additional complexity to the codebase for an edge case that is very rarely going to occur, so I don't think it's worth it 👍

**Pull request merged**
